openapi: 3.2.0
info:
  version: 1.0.0
  x-release: v4
  title: AWS Marketplace Catalog Service CancelChangeSet#catalog&changeSetId Describe Change Set#catalog&change Set ID API
  description: <p>Catalog API actions allow you to manage your entities through list, describe, and update capabilities. An entity can be a product or an offer on AWS Marketplace. </p> <p>You can automate your entity update process by integrating the AWS Marketplace Catalog API with your AWS Marketplace product build or deployment pipelines. You can also create your own applications on top of the Catalog API to manage your products on AWS Marketplace.</p>
  x-logo:
    url: https://twitter.com/awscloud/profile_image?size=original
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: marketplace-catalog
  x-aws-signingName: aws-marketplace
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/marketplace-catalog-2018-09-17.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://catalog.marketplace.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Marketplace Catalog multi-region endpoint
- url: https://catalog.marketplace.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Marketplace Catalog multi-region endpoint
- url: http://catalog.marketplace.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Marketplace Catalog endpoint for China (Beijing) and China (Ningxia)
- url: https://catalog.marketplace.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Marketplace Catalog endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: DescribeChangeSet#catalog&changeSetId
paths:
  /DescribeChangeSet#catalog&changeSetId:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    get:
      operationId: DescribeChangeSet
      description: Provides information about a given change set.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DescribeChangeSetResponse'
        '480':
          description: InternalServiceException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServiceException'
        '481':
          description: AccessDeniedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessDeniedException'
        '482':
          description: ValidationException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationException'
        '483':
          description: ResourceNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundException'
        '484':
          description: ThrottlingException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThrottlingException'
      parameters:
      - name: catalog
        in: query
        required: true
        description: 'Required. The catalog related to the request. Fixed value: <code>AWSMarketplace</code> '
        schema:
          type: string
          pattern: ^[a-zA-Z]+$
          minLength: 1
          maxLength: 64
      - name: changeSetId
        in: query
        required: true
        description: Required. The unique identifier for the <code>StartChangeSet</code> request that you want to describe the details for.
        schema:
          type: string
          pattern: ^[\w\-]+$
          minLength: 1
          maxLength: 255
      summary: Amazon Marketplace Describe Change Set
      tags:
      - DescribeChangeSet#catalog&changeSetId
components:
  schemas:
    ValidationException: {}
    ErrorCodeString:
      type: string
      pattern: ^[a-zA-Z_]+$
      minLength: 1
      maxLength: 72
    ChangeSummary:
      type: object
      properties:
        ChangeType:
          allOf:
          - $ref: '#/components/schemas/ChangeType'
          - description: The type of the change.
        Entity:
          allOf:
          - $ref: '#/components/schemas/Entity'
          - description: The entity to be changed.
        Details:
          allOf:
          - $ref: '#/components/schemas/Json'
          - description: This object contains details specific to the change type of the requested change.
        ErrorDetailList:
          allOf:
          - $ref: '#/components/schemas/ErrorDetailList'
          - description: An array of <code>ErrorDetail</code> objects associated with the change.
        ChangeName:
          allOf:
          - $ref: '#/components/schemas/ChangeName'
          - description: Optional name for the change.
      description: This object is a container for common summary information about the change. The summary doesn't contain the whole change structure.
    Identifier:
      type: string
      pattern: ^[\w\-@]+$
      minLength: 1
      maxLength: 255
    AccessDeniedException: {}
    ChangeSetName:
      type: string
      pattern: ^[\w\s+=.:@-]+$
      minLength: 1
      maxLength: 100
    InternalServiceException: {}
    ChangeName:
      type: string
      pattern: ^[a-zA-Z]$
      minLength: 1
      maxLength: 72
    FailureCode:
      type: string
      enum:
      - CLIENT_ERROR
      - SERVER_FAULT
    ErrorDetailList:
      type: array
      items:
        $ref: '#/components/schemas/ErrorDetail'
    ResourceId:
      type: string
      pattern: ^[\w\-]+$
      minLength: 1
      maxLength: 255
    ChangeSetDescription:
      type: array
      items:
        $ref: '#/components/schemas/ChangeSummary'
    Json:
      type: string
      pattern: ^[\s]*\{[\s\S]*\}[\s]*$
      minLength: 2
      maxLength: 16384
    ThrottlingException: {}
    EntityType:
      type: string
      pattern: ^[a-zA-Z]+$
      minLength: 1
      maxLength: 255
    ChangeType:
      type: string
      pattern: ^[A-Z][\w]*$
      minLength: 1
      maxLength: 255
    DateTimeISO8601:
      type: string
      pattern: ^([\d]{4})\-(1[0-2]|0[1-9])\-(3[01]|0[1-9]|[12][\d])T(2[0-3]|[01][\d]):([0-5][\d]):([0-5][\d])Z$
      minLength: 20
      maxLength: 20
    ARN:
      type: string
      pattern: ^[a-zA-Z0-9:*/-]+$
      minLength: 1
      maxLength: 2048
    ResourceNotFoundException: {}
    DescribeChangeSetResponse:
      type: object
      properties:
        ChangeSetId:
          allOf:
          - $ref: '#/components/schemas/ResourceId'
          - description: Required. The unique identifier for the change set referenced in this request.
        ChangeSetArn:
          allOf:
          - $ref: '#/components/schemas/ARN'
          - description: The ARN associated with the unique identifier for the change set referenced in this request.
        ChangeSetName:
          allOf:
          - $ref: '#/components/schemas/ChangeSetName'
          - description: The optional name provided in the <code>StartChangeSet</code> request. If you do not provide a name, one is set by default.
        StartTime:
          allOf:
          - $ref: '#/components/schemas/DateTimeISO8601'
          - description: 'The date and time, in ISO 8601 format (2018-02-27T13:45:22Z), the request started. '
        EndTime:
          allOf:
          - $ref: '#/components/schemas/DateTimeISO8601'
          - description: 'The date and time, in ISO 8601 format (2018-02-27T13:45:22Z), the request transitioned to a terminal state. The change cannot transition to a different state. Null if the request is not in a terminal state. '
        Status:
          allOf:
          - $ref: '#/components/schemas/ChangeStatus'
          - description: The status of the change request.
        FailureCode:
          allOf:
          - $ref: '#/components/schemas/FailureCode'
          - description: Returned if the change set is in <code>FAILED</code> status. Can be either <code>CLIENT_ERROR</code>, which means that there are issues with the request (see the <code>ErrorDetailList</code>), or <code>SERVER_FAULT</code>, which means that there is a problem in the system, and you should retry your request.
        FailureDescription:
          allOf:
          - $ref: '#/components/schemas/ExceptionMessageContent'
          - description: Returned if there is a failure on the change set, but that failure is not related to any of the changes in the request.
        ChangeSet:
          allOf:
          - $ref: '#/components/schemas/ChangeSetDescription'
          - description: An array of <code>ChangeSummary</code> objects.
    ChangeStatus:
      type: string
      enum:
      - PREPARING
      - APPLYING
      - SUCCEEDED
      - CANCELLED
      - FAILED
    Entity:
      type: object
      required:
      - Type
      properties:
        Type:
          allOf:
          - $ref: '#/components/schemas/EntityType'
          - description: The type of entity.
        Identifier:
          allOf:
          - $ref: '#/components/schemas/Identifier'
          - description: The identifier for the entity.
      description: 'An entity contains data that describes your product, its supported features, and how it can be used or launched by your customer. '
    ErrorDetail:
      type: object
      properties:
        ErrorCode:
          allOf:
          - $ref: '#/components/schemas/ErrorCodeString'
          - description: The error code that identifies the type of error.
        ErrorMessage:
          allOf:
          - $ref: '#/components/schemas/ExceptionMessageContent'
          - description: The message for the error.
      description: Details about the error.
    ExceptionMessageContent:
      type: string
      pattern: ^(.)+$
      minLength: 1
      maxLength: 2048
  parameters:
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/marketplace/
